version: '3.8'

services:
  db:
    image: fernandoocana0409/library_db:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - webnet

  backend:
    image: fernandoocana0409/library_backend:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - webnet

  frontend:
    image: fernandoocana0409/library_frontend:latest
    depends_on:
      - backend
    environment:
      - REACT_APP_URL_BACKEND=http://34.123.99.167:8080
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - db
    networks:
      - webnet

networks:
  webnet:
